### ISSUE TITLE
Article Suggestion - Creating a Simple REPL Environment in GO

### ISSUE THREAD

**Issue by mdwiltfong** [bootdotdev/blog#101]
This issue was inspired from doing the PokeDex challenge in boot.dev. Although the challenge encourages learners to look up additional information through Google, I think this is a missed opportunity for boot.dev. Primarily because when googling "repl in GO" someone else's blog comes up as the second item: https://www.desmondcheong.com/blog/2021/05/05/writing-a-simple-repl-in-go/

This is why I think the blog should have a similar article. Of course the article shouldn't disclose information in the lesson that only paid learners should see. 

I would also be interested in writing this article if it's found to be beneficial!

**Comment by wagslane** [comment]
We'll think about this, thanks!
