### ISSUE TITLE
Article on Node.js Event Loop

### ISSUE THREAD

**Issue by mdwiltfong** [bootdotdev/blog#110]
Understanding the NodeJS event loop is an advanced concept in modern day JavaScript. It would help the community and the blog as a whole if we included an article about this. I would be glad to lead this!

**Comment by mrbelane** [comment]
I highly recommend reading this article: [How V8 JavaScript Engine Works](https://cabulous.medium.com/how-v8-javascript-engine-works-5393832d80a7). It provides an excellent overview and detailed insights into the internals of V8.

**Comment by skovranek** [comment]
@mdwiltfong you're welcome to submit an article. There are some excellent videos on youtube that might take care of that need, though:

https://www.youtube.com/results?search_query=node+event+loop
