### ISSUE TITLE
Typo in WHY WE FORCE YOU TO LEARN MULTIPLE PROGRAMMING LANGUAGES

### ISSUE THREAD

**Issue by TavishLaughlin** [bootdotdev/blog#116]
There is a typo in the paragraph that is subtitled: WHY GO?

In between the first and second sentences, there is a missing space before the word "Go".

WHY GO?
[🔗](https://blog.boot.dev/education/learn-multiple-programming-languages/#why-go)
Our CS degree has an emphasis on backend programming, and I’ve personally had tremendous success with Go as a backend **language.Go** will make it easier to teach things like concurrency, compilers, and distributed systems than some of the other choices I’ve thought about. I do think we might eventually have a Rust course that goes to an even lower level in terms of manual memory management, but I haven’t decided on that yet.

**Comment by Luke-McMahon** [comment]
I've fixed this in: #125
