### ISSUE TITLE
 Broken Link in Golang Article

### ISSUE THREAD

**Issue by Numeez** [bootdotdev/blog#133]
Description:
I came across an article on your site about implementing Merge Sort in Golang, which mentioned a resource link (https://www.golanginterview.dev/questions/) as a great resource for people interested in learning Golang. However, this link does not exist and returns a 404 error.

Steps to Reproduce:

Visit the article on Merge Sort in Golang.
Click on the provided resource link (https://www.golanginterview.dev/questions/).
Expected Behavior:
The link should lead to a page with relevant information about Golang interview questions.

Actual Behavior:
The link returns a 404 error, indicating the page does not exist.

Proposed Solution:
Please update the article with the correct link or provide the correct resource URL for Golang interview questions.

Thank you for your attention to this matter.

**Comment by wagslane** [comment]
ty
