### ISSUE TITLE
probable misspelling of "Van Gogh"

### ISSUE THREAD

**Issue by evrende** [bootdotdev/blog#152]
Hi all,

Thanks to Lane Wagner for his post about preferring to work on the backend. I found only one questionable item, right under [https://blog.boot.dev/backend/why-i-prefer-backend/#i-love-building-my-own-stuff-sans-the-ui]: "Van Goph" -- which I'm guessing is a misspelling of the famed painter's name.

Thanks,
evrende

**Comment by wagslane** [comment]
it looks right to me: https://en.wikipedia.org/wiki/Vincent_van_Gogh

**Comment by evrende** [comment]
I just cleared my browser cache, but still see

[cid:695fbc41-5238-4022-9977-d9ba189938bd]
Not a big deal. But I'm all for spellcheckers.

Regards,
evrende
________________________________

**Comment by wagslane** [comment]
Did you mean to upload something? I might just not be understanding what you're referring to: "Van Goph" is what I see in the blog, and it's how it's spelled on wikipedia

**Comment by evrende** [comment]
All I meant to include was one screenshot. At issue is the second-to-last character in "Van Goph"; recruiting another set of eyeballs might help to clarify what I was writing about.

https://en.wikipedia.org/wiki/Vincent_van_Gogh

Best,
evrende
________________________________

**Comment by evrende** [comment]
In other words, if you go to the HTML for the page at https://blog.boot.dev/backend/why-i-prefer-backend/ and change the string "Goph" to "Gogh", then this spelling will come into alignment with the one we find at Wikipedia and other places, e,g, https://www.vangoghmuseum.nl/en/art-and-stories/art/vincent-van-gogh. And my obsessing mind will be stilled, at least with regard to this matter. On inspection, we see that the letter "p" is different than the letter "g".

Thank you for tolerating these messages. You can expect this one to be my last on this subject.

Yours truly,
evrende, aka Todd Shirley
________________________________
