### ISSUE TITLE
Non existent URL on the HTTP Live Streaming Go blog

### ISSUE THREAD

**Issue by ShabarishRamaswamy** [bootdotdev/blog#154]
Hey,
I was reading the following blog:
https://blog.boot.dev/golang/golang-video-stream-server/

The bottom links to:
https://hls-js-latest.netlify.com/demo/

This is no longer active and links to a dead page.

Instead, a minimal HTML based HLS player can be linked, like this one:
https://github.com/video-dev/hls.js/blob/master/docs/API.md#first-step-setup-and-support

**Comment by wagslane** [comment]
Fixed, thanks!
