### ISSUE TITLE
Typo: blog JSON Go Guide

### ISSUE THREAD

**Issue by skovranek** [bootdotdev/blog#54]
Location: Blog The Ultimate Guide to JSON in Go
Link: https://blog.boot.dev/golang/json-golang/#example---go-json-http-server

Typo:
I typically start by writing two little helper functions, respondWithJSON and responsdWithError.

Fixed: 
I typically start by writing two little helper functions, respondWithJSON and respondWithError.

**Comment by wagslane** [comment]
Thanks!
