### ISSUE TITLE
typo: Programming Types

### ISSUE THREAD

**Issue by skovranek** [bootdotdev/blog#56]
Blog post: Programming Types and (Incorrect) Mindsets
link: https://blog.boot.dev/clean-code/reacting-to-programming-types-and-mindsets/#argument-1-simpler-syntax
Typo:
Python makes for an amazing environment in which to learn programming, bsut that’s despite the dynamic typing, not because of it.
Fixed:
Python makes for an amazing environment in which to learn programming, but that’s despite the dynamic typing, not because of it.

**Comment by wagslane** [comment]
Thanks!
