### ISSUE TITLE
Omitting c# seems inaccurate considering the source material

### ISSUE THREAD

**Issue by NidusUmbra** [bootdotdev/blog#60]
The omission of C# as a backend language is simply not representative of the survey, even in a list restricted to just 8 entries.

In the list of most commonly used languages, it scores at exactly 8
(https://survey.stackoverflow.co/2022/#programming-scripting-and-markup-languages)

It could end here but since it is not a list explicitly for 'backend languages' here are some additional arguments: 

Databases - Microsoft SQL server, ranked at 4. SQL Server Management Objects are coded using C#. (It's also at 7 in most loved/dreaded)
 
Frameworks and technologies - ASP.NET core ranked at 7, ASP.NET ranked at 8 - one of the extensible languages is C# (the others being mostly an afterthought). Core is also at 4 in most loved/dreaded.

Under 'Other Frameworks and Technologies' .NET ranks at 1! Make of this what you will since not only c# is supported here, but c# is at the heart of .NET, challenged only by other .NET languages, and by c++/c.

Most popular IDE rank 2 is visual studio. If you want to make extensions for it you must use c# in some or most of your design. Not many devs use only the bare VS, having some extensions is the standard and devs are themselves producing these extensions.

Windows is the most favored OS. If you want to make production utilities for it c#, c, c++ and VB are the ones to use.

ADDITIONALLY: When filtering for only 'professional developers', most of the above jump one point up!

So unless someone can find an entry that really tanks the balance (lowest I could find was 10), it should realistically be in the list.

https://survey.stackoverflow.co/2022/#overview

**Comment by wagslane** [comment]
Thanks!
