### ISSUE TITLE
Update to "Keyup and Keydown Event Handlers in Vue 3" required

### ISSUE THREAD

**Issue by darrylnoakes** [bootdotdev/blog#65]
In [this article](https://blog.boot.dev/javascript/vue-key-events/) about keyboard events, you state that the docs "gloss over" key shortcut aliases.

> According [to the docs](https://vuejs.org/guide/essentials/event-handling.html#key-modifiers), aliases are provided for common keys:
> ...
> But what if you want to capture a different key? Well, unfortunately, the docs mostly gloss over this use case. At least I couldn’t find where it was addressed.
>
> I did however find some useful information in the [Vue2 -> Vue3 migration guide](https://v3-migration.vuejs.org/breaking-changes/keycode-modifiers.html). Turns out that can use the kebab-case name for any key you want to use as a modifier.

The docs have since been updated, and now clearly state this:

> When listening for keyboard events, we often need to check for specific keys. Vue allows adding key modifiers for `v-on` or `@` when listening for key events:
> 
> ```html
> 
> <input @keyup.enter="submit" />
> ```
> 
> You can directly use any valid key names exposed via [`KeyboardEvent.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values) as modifiers by converting them to kebab-case.
> 
> ```html
> <input @keyup.page-down="onPageDown" />
> ```
> In the above example, the handler will only be called if `$event.key` is equal to 'PageDown'.

There then follows some short sections on aliases and modifiers.

Can the article please be updated?

**Comment by wagslane** [comment]
Thanks!
