### ISSUE TITLE
to to

### ISSUE THREAD

**Issue by KarLagerfeld** [bootdotdev/blog#67]
"Who wants to to invent the wheel over and over again?"

I understand that, because of how the word sounds, writing two to's is tempting, but part of growing up is not giving in to every temptation in public xoxoxo

![grafik](https://github.com/bootdotdev/blog/assets/109218445/fa3bd7a2-1ddb-4ff7-a2c0-dffb35348551)

**Comment by wagslane** [comment]
thanks!
