### ISSUE TITLE
camelCase does require using the shift key

### ISSUE THREAD

**Issue by rshmhrj** [bootdotdev/blog#68]
Hi Lane -- just discovered the blog via this masterpiece: https://www.youtube.com/watch?v=KzV0mTqBcZA

Apologies in advance for the SUPER nit-picky thing here...

In the [casing article](https://blog.boot.dev/clean-code/casings-in-coding/), it states: 

> Camel case doesn’t require the use of the `shift` key, and uses one less keystroke.

It's definitely one less keystroke, but we still need to capitalize the second word in camel case -- so smacking `shift` is still necessary in both snakeCase and camel_case.

Maybe this rephrasing might be okay?

> While both snake_case and camelCase both require the use of the `shift` key, camelCase uses one less keystroke.

Thanks again for the awesome articles & for sharing your strong opinions!

**Comment by wagslane** [comment]
Thanks! fixed
