### ISSUE TITLE
Typo in "HOW TO BUILD THE BEST GITHUB PROFILE FOR YOUR JOB SEARCH"

### ISSUE THREAD

**Issue by datadeverik** [bootdotdev/blog#71]
The logic isn't quite right here:

"""
There really isn’t any excuse to just hide your old code that you don’t plan on maintaining behind a privacy flag. 
"""

I think it should be

"""
There really isn’t any excuse to [not] just hide your old code that you don’t plan on maintaining behind a privacy flag. 
""

**Comment by wagslane** [comment]
Thanks! fixed
