### ISSUE TITLE
Typo in "SHOULD YOU COMMIT THE VENDOR FOLDER IN GO?"

### ISSUE THREAD

**Issue by minusung** [bootdotdev/blog#73]
link:
https://blog.boot.dev/golang/should-you-commit-the-vendor-folder-in-go/#:~:text=js%20land%2C%20Golang%27s%20vendor%20directory,go%20build%20command%20is%20run.

The #2 right before FINAL VERDICT says 
```
You’re CI/CD pipelines don’t need access to remote repos, or permissions to remote private repos to build and test your code.
```

Should be "**Your** CI/CD pipelines"

**Comment by wagslane** [comment]
Thanks! fixed
