### ISSUE TITLE
Typo in LEARN TO CODE THE SLOW WAY

### ISSUE THREAD

**Issue by yanukadeneth99** [bootdotdev/blog#76]
Link : https://blog.boot.dev/education/learn-to-code-the-slow-way/#:~:text=If%20you%20knew%20exactly%20which%20concepts%20you%E2%80%99d%20need%20to%20master%20to%20pass%20your%20first%20interview%2C%20then%20you%20could%20might%20be%20able%20to%20find%20an%20effective%20shortcut.

"If you knew exactly which concepts you’d need to master to pass your first interview, then you ~~could~~ might be able to find an effective shortcut."

**Comment by wagslane** [comment]
Thanks!
