### ISSUE TITLE
Code example does not compile in Wrapping Errors in Go - How to Handle Nested Errors

### ISSUE THREAD

**Issue by KinNeko-De** [bootdotdev/blog#77]
Hey.. the code example from your article: https://blog.boot.dev/golang/wrapping-errors-in-go-how-to-handle-nested-errors/ does not compile:

``` go
func getNumberFromStdIn() (int, error) {
	reader := bufio.NewReader(os.Stdin)
	text, _, err := reader.ReadLine()
	if err != nil {
		return 0, fmt.Errorf("reader.ReadLine: %w", fName, err)
	}
	i, err := strconv.Atoi(string(text))
	if err != nil {
		return 0, fmt.Errorf("strconv.Atoi: %w", fName, err)
	}
	err = isInRange(i)
	if err != nil {
		return 0, fmt.Errorf("isInRange: %w", fName, err)
	}
	return i, nil
}

func runMainThread() error {
	i, err := getNumberFromStdIn()
	if err != nil{
		return fmt.Errorf("getNumberFromStdIn: %w")
	}
}
```

`fmt.Errorf("reader.ReadLine: %w", fName, err)` 
`fmt.Errorf("strconv.Atoi: %w", fName, err)`
`fmt.Errorf("isInRange: %w", fName, err)`
fName is never defined, fmt.Errorf expects exactly one additional value

`fmt.Errorf("getNumberFromStdIn: %w")`
fmt.Errorf expects exactly one additional value, i think you want to pass `err` here

Anyways.. you helped me

**Comment by wagslane** [comment]
Thanks, fixed!
