### ISSUE TITLE
Typo in the JWT lifecycle image ('repeasts')

### ISSUE THREAD

**Issue by aditkarmu** [bootdotdev/blog#78]
In this image, there is a typo in the word 'repeats'-
![image](https://github.com/bootdotdev/blog/assets/136361910/90b5fd85-0406-4457-b881-37a5a12f1055)

Here is the link to that webpage- https://blog.boot.dev/cryptography/hmac-and-macs-in-jwts/

**Comment by aditkarmu** [comment]
Link to the webpage- https://blog.boot.dev/cryptography/hmac-and-macs-in-jwts/

**Comment by wagslane** [comment]
Thanks! will fix
