### ISSUE TITLE
Typo in "TOP 8 BENEFITS OF FUNCTIONAL PROGRAMMING"

### ISSUE THREAD

**Issue by BittahD** [bootdotdev/blog#79]
Small typo (OT, should read IT) on the [7th](https://blog.boot.dev/clean-code/benefits-of-functional-programming/#7-recursion-is-simpler-though-not-necessarily-easier-to-learn) "benefit" second paragraph of the article.

**Comment by wagslane** [comment]
Fixed thanks!
