### ISSUE TITLE
404 page when clicking on the quest board link (which hasnt been active in a while)

### ISSUE THREAD

**Issue by wcwagner22** [bootdotdev/blog#88]
When you go to:

https://blog.boot.dev/wiki/the-game/#quests

and click any hyperlinked "questboard":

https://www.boot.dev/questboard

You are receiving a HTTP 404 error: 

https://discord.com/channels/551921866173054977/553576599723966475/1180483970547322890

**Comment by wagslane** [comment]
To resolve: Remove the link to quest board on the blog
