### ISSUE TITLE
Typo in "Don't Go To Casting Hell - Use Default Native Types in Go"

### ISSUE THREAD

**Issue by Zachary-Vavrek** [bootdotdev/blog#98]
Link: https://blog.boot.dev/golang/default-native-types-golang/#why-do-we-care-about-defaults

Page reads:
> while `int64` ranges from `-9,223,372,036,854,775,808` to `9,223,372,036,854,775,807. At the same time, int8` uses a single byte while `int64` uses 8x that.

Should read:
> while `int64` ranges from `-9,223,372,036,854,775,808` to `9,223,372,036,854,775,807`. At the same time, `int8` uses a single byte while `int64` uses 8x that.

**Comment by wagslane** [comment]
Fixed! thanks
